name: diarykuh
description: A simple diary application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
