// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj_Vy7_RBfru7mGaW5devItje63ScnVjE',
    appId: '1:777760415815:web:8356f2fdbcd27329cf1162',
    messagingSenderId: '777760415815',
    projectId: 'diarykuh',
    authDomain: 'diarykuh.firebaseapp.com',
    storageBucket: 'diarykuh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsvJiPsRb9ReMaqQtYBLM4hoOvUtjuSg',
    appId: '1:777760415815:android:ccd725f16643ff98cf1162',
    messagingSenderId: '777760415815',
    projectId: 'diarykuh',
    storageBucket: 'diarykuh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9jkecA37Q-UGlrqOUudR9uy-gIpn18o',
    appId: '1:777760415815:ios:716f05dd23b16476cf1162',
    messagingSenderId: '777760415815',
    projectId: 'diarykuh',
    storageBucket: 'diarykuh.firebasestorage.app',
    iosBundleId: 'com.example.diarykuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ9jkecA37Q-UGlrqOUudR9uy-gIpn18o',
    appId: '1:777760415815:ios:716f05dd23b16476cf1162',
    messagingSenderId: '777760415815',
    projectId: 'diarykuh',
    storageBucket: 'diarykuh.firebasestorage.app',
    iosBundleId: 'com.example.diarykuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj_Vy7_RBfru7mGaW5devItje63ScnVjE',
    appId: '1:777760415815:web:e5a4029b11061bbbcf1162',
    messagingSenderId: '777760415815',
    projectId: 'diarykuh',
    authDomain: 'diarykuh.firebaseapp.com',
    storageBucket: 'diarykuh.firebasestorage.app',
  );
}
